apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pogues.api.fullname" . }}
  labels:
    {{- include "pogues.api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pogues.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pogues.api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pogues.api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
          - name: FR_INSEE_POGUES_FORCE_SSL
            value: {{ .Values.api.environment.ssl | quote}}
          - name: FR_INSEE_POGUES_LOG_CONFIGURATION
            value: {{ .Values.api.environment.log.configuration| quote}}
          - name: FR_INSEE_POGUES_API_HOST
            value: {{ .Values.api.environment.api.host | quote}}
          - name: FR_INSEE_POGUES_API_NAME
            value: {{ .Values.api.environment.api.name | quote}}
          - name: FR_INSEE_POGUES_API_SCHEME
            value: {{ .Values.api.environment.api.scheme | quote}}
          - name: FR_INSEE_POGUES_PERSISTENCE_DATABASE_HOST
            value: {{ .Values.api.environment.persistence.database.host | quote}}
          - name: FR_INSEE_POGUES_PERSISTENCE_DATABASE_PORT
            value: {{ .Values.api.environment.persistence.database.port | quote}}
          - name: FR_INSEE_POGUES_PERSISTENCE_DATABASE_SCHEMA
            value: {{ .Values.postgresql.auth.database | quote}}
          - name: FR_INSEE_POGUES_PERSISTENCE_DATABASE_USER
            value: {{ .Values.postgresql.auth.username | quote}}
          - name: FR_INSEE_POGUES_PERSISTENCE_DATABASE_PASSWORD
            value: {{ .Values.postgresql.auth.password | quote}}
          - name: FR_INSEE_POGUES_PERSISTENCE_DATABASE_DRIVER
            value: {{ .Values.api.environment.persistence.database.driver | quote}}
          - name: FR_INSEE_POGUES_PERSISTENCE_DATABASE_TABLE
            value: {{ .Values.api.environment.persistence.database.table | quote}}
          - name: FR_INSEE_POGUES_AUTHENTICATION
            value: {{ .Values.api.environment.authentification | quote}}
          - name: FR_INSEE_POGUES_ROLE_ADMIN
            value: {{ .Values.api.environment.role.admin | quote}}
          - name: FR_INSEE_POGUES_ROLE_USER
            value: {{ .Values.api.environment.role.user | quote}}
          - name: FR_INSEE_POGUES_API_REMOTE_METADATA_URL
            value: {{ .Values.api.environment.remote.metadata.url | quote}}
          - name: FR_INSEE_POGUES_API_REMOTE_STROMAE_HOST
            value: {{ .Values.api.environment.remote.stromae.host | quote}}
          - name: FR_INSEE_POGUES_API_REMOTE_STROMAE_VIS_PATH
            value: {{ .Values.api.environment.remote.stromae.vis.path | quote}}
          - name: FR_INSEE_POGUES_API_REMOTE_STROMAE_ORBEON_HOST
            value: {{ .Values.api.environment.remote.stromae.orbeon.host | quote}}
          - name: FR_INSEE_POGUES_API_REMOTE_QUEEN_HOST
            value: {{ .Values.api.environment.remote.queen.host | quote}}
          - name: FR_INSEE_POGUES_API_REMOTE_QUEEN_VIS_PATH
            value: {{ .Values.api.environment.remote.queen.vis.path | quote}}
          - name: FR_INSEE_POGUES_API_REMOTE_STROMAEV2_VIS_URL
            value: {{ .Values.api.environment.remote.stromaev2.vis.url | quote}}
          - name: FR_INSEE_POGUES_API_REMOTE_ENO_HOST
            value: {{ .Values.api.environment.remote.eno.host | quote}}
          - name: FR_INSEE_POGUES_API_REMOTE_ENO_SCHEME
            value: {{ .Values.api.environment.remote.eno.scheme | quote}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
