apiVersion: v2
name: survey-designer
description: A Helm chart for Kubernetes

dependencies:
  - name: pogues
    condition: pogues.enabled
    version: 0.0.1
    repository: "file://../pogues"
  - name: eno-ws
    condition: eno-ws.enabled
    version: 0.1.0
    repository: "file://../eno-ws"
  - name: ddi-access-services
    condition: ddi-access-services.enabled
    version: 0.1.0
    repository: "file://../ddi-access-services"
  - name: queen
    condition: queen.enabled
    version: 0.3.0
    repository: "https://inseefr.github.io/Helm-Charts"
  - name: stromae-v2
    condition: stromae-v2.enabled
    version: 0.5.6
    repository: "https://inseefr.github.io/Helm-Charts"

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
